name: Build & Publish Release APK

# on:
#   push:
#     tags:
#       - '*'
      
      
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
      
      
      
      
      
      
      

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build Release APK
      run: ./gradlew assembleRelease
      
            find -name "*.apk"

#     - name: Releasing using Hub
#       uses: r0user/release-apk@main
#       env:
# #        GITHUB_TOKEN: ${{ secrets.TOKEN }}
#        GITHUB_TOKEN: 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
       
       
#        APP_FOLDER: app
    - name: Upload APK

      uses: actions/upload-artifact@v2
      with:
          # 设置压缩文件的名称，在控制台会得到WhuHelper-debug.zip文件的下载链接
          # 下载后解压缩，里面直接可以看到app-debug.apk，没有其他东西
          name: WhuHelper-debug
          path: find . -name "*.apk" -printf "%p\n"

